/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router. Do not edit manually.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedNodesIndexRouteImport } from './routes/_authed/nodes/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedPlansIndexRouteImport } from './routes/_authed/plans/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/_authed/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNodesIndexRoute = AuthedNodesIndexRouteImport.update({
  id: '/_authed/nodes/',
  path: '/nodes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/_authed/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansIndexRoute = AuthedPlansIndexRouteImport.update({
  id: '/_authed/plans/',
  path: '/plans/',
  getParentRoute: () => AuthedRoute,
} as any)

export const routeTree = rootRouteImport.addChildren([
  LoginRoute,
  AuthedRoute.addChildren([
    AuthedIndexRoute,
    AuthedNodesIndexRoute,
    AuthedClientsIndexRoute,
    AuthedPlansIndexRoute,
  ]),
])
