/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedPortalIndexRouteImport } from './routes/_authed/portal/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedPortalFilesIndexRouteImport } from './routes/_authed/portal/files/index'
import { Route as AuthedPortalDomainsIndexRouteImport } from './routes/_authed/portal/domains/index'
import { Route as AuthedPortalDatabasesIndexRouteImport } from './routes/_authed/portal/databases/index'
import { Route as AuthedAdminPlansIndexRouteImport } from './routes/_authed/admin/plans/index'
import { Route as AuthedAdminNodesIndexRouteImport } from './routes/_authed/admin/nodes/index'
import { Route as AuthedAdminClientsIndexRouteImport } from './routes/_authed/admin/clients/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPortalIndexRoute = AuthedPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPortalFilesIndexRoute = AuthedPortalFilesIndexRouteImport.update({
  id: '/portal/files/',
  path: '/portal/files/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPortalDomainsIndexRoute =
  AuthedPortalDomainsIndexRouteImport.update({
    id: '/portal/domains/',
    path: '/portal/domains/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPortalDatabasesIndexRoute =
  AuthedPortalDatabasesIndexRouteImport.update({
    id: '/portal/databases/',
    path: '/portal/databases/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminPlansIndexRoute = AuthedAdminPlansIndexRouteImport.update({
  id: '/admin/plans/',
  path: '/admin/plans/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminNodesIndexRoute = AuthedAdminNodesIndexRouteImport.update({
  id: '/admin/nodes/',
  path: '/admin/nodes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminClientsIndexRoute = AuthedAdminClientsIndexRouteImport.update({
  id: '/admin/clients/',
  path: '/admin/clients/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/portal/': typeof AuthedPortalIndexRoute
  '/admin/clients/': typeof AuthedAdminClientsIndexRoute
  '/admin/nodes/': typeof AuthedAdminNodesIndexRoute
  '/admin/plans/': typeof AuthedAdminPlansIndexRoute
  '/portal/databases/': typeof AuthedPortalDatabasesIndexRoute
  '/portal/domains/': typeof AuthedPortalDomainsIndexRoute
  '/portal/files/': typeof AuthedPortalFilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/portal': typeof AuthedPortalIndexRoute
  '/admin/clients': typeof AuthedAdminClientsIndexRoute
  '/admin/nodes': typeof AuthedAdminNodesIndexRoute
  '/admin/plans': typeof AuthedAdminPlansIndexRoute
  '/portal/databases': typeof AuthedPortalDatabasesIndexRoute
  '/portal/domains': typeof AuthedPortalDomainsIndexRoute
  '/portal/files': typeof AuthedPortalFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/portal/': typeof AuthedPortalIndexRoute
  '/_authed/admin/clients/': typeof AuthedAdminClientsIndexRoute
  '/_authed/admin/nodes/': typeof AuthedAdminNodesIndexRoute
  '/_authed/admin/plans/': typeof AuthedAdminPlansIndexRoute
  '/_authed/portal/databases/': typeof AuthedPortalDatabasesIndexRoute
  '/_authed/portal/domains/': typeof AuthedPortalDomainsIndexRoute
  '/_authed/portal/files/': typeof AuthedPortalFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/'
    | '/portal/'
    | '/admin/clients/'
    | '/admin/nodes/'
    | '/admin/plans/'
    | '/portal/databases/'
    | '/portal/domains/'
    | '/portal/files/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/portal'
    | '/admin/clients'
    | '/admin/nodes'
    | '/admin/plans'
    | '/portal/databases'
    | '/portal/domains'
    | '/portal/files'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/admin/'
    | '/_authed/portal/'
    | '/_authed/admin/clients/'
    | '/_authed/admin/nodes/'
    | '/_authed/admin/plans/'
    | '/_authed/portal/databases/'
    | '/_authed/portal/domains/'
    | '/_authed/portal/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/portal/': {
      id: '/_authed/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthedPortalIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/portal/files/': {
      id: '/_authed/portal/files/'
      path: '/portal/files'
      fullPath: '/portal/files/'
      preLoaderRoute: typeof AuthedPortalFilesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/portal/domains/': {
      id: '/_authed/portal/domains/'
      path: '/portal/domains'
      fullPath: '/portal/domains/'
      preLoaderRoute: typeof AuthedPortalDomainsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/portal/databases/': {
      id: '/_authed/portal/databases/'
      path: '/portal/databases'
      fullPath: '/portal/databases/'
      preLoaderRoute: typeof AuthedPortalDatabasesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/plans/': {
      id: '/_authed/admin/plans/'
      path: '/admin/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AuthedAdminPlansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/nodes/': {
      id: '/_authed/admin/nodes/'
      path: '/admin/nodes'
      fullPath: '/admin/nodes/'
      preLoaderRoute: typeof AuthedAdminNodesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/clients/': {
      id: '/_authed/admin/clients/'
      path: '/admin/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthedAdminClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedPortalIndexRoute: typeof AuthedPortalIndexRoute
  AuthedAdminClientsIndexRoute: typeof AuthedAdminClientsIndexRoute
  AuthedAdminNodesIndexRoute: typeof AuthedAdminNodesIndexRoute
  AuthedAdminPlansIndexRoute: typeof AuthedAdminPlansIndexRoute
  AuthedPortalDatabasesIndexRoute: typeof AuthedPortalDatabasesIndexRoute
  AuthedPortalDomainsIndexRoute: typeof AuthedPortalDomainsIndexRoute
  AuthedPortalFilesIndexRoute: typeof AuthedPortalFilesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedPortalIndexRoute: AuthedPortalIndexRoute,
  AuthedAdminClientsIndexRoute: AuthedAdminClientsIndexRoute,
  AuthedAdminNodesIndexRoute: AuthedAdminNodesIndexRoute,
  AuthedAdminPlansIndexRoute: AuthedAdminPlansIndexRoute,
  AuthedPortalDatabasesIndexRoute: AuthedPortalDatabasesIndexRoute,
  AuthedPortalDomainsIndexRoute: AuthedPortalDomainsIndexRoute,
  AuthedPortalFilesIndexRoute: AuthedPortalFilesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
