/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router. Do not edit manually.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedDomainsIndexRouteImport } from './routes/_authed/domains/index'
import { Route as AuthedDatabasesIndexRouteImport } from './routes/_authed/databases/index'
import { Route as AuthedFilesIndexRouteImport } from './routes/_authed/files/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/_authed/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsIndexRoute = AuthedDomainsIndexRouteImport.update({
  id: '/_authed/domains/',
  path: '/domains/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDatabasesIndexRoute = AuthedDatabasesIndexRouteImport.update({
  id: '/_authed/databases/',
  path: '/databases/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFilesIndexRoute = AuthedFilesIndexRouteImport.update({
  id: '/_authed/files/',
  path: '/files/',
  getParentRoute: () => AuthedRoute,
} as any)

export const routeTree = rootRouteImport.addChildren([
  LoginRoute,
  AuthedRoute.addChildren([
    AuthedIndexRoute,
    AuthedDomainsIndexRoute,
    AuthedDatabasesIndexRoute,
    AuthedFilesIndexRoute,
  ]),
])
