/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedFilesIndexRouteImport } from './routes/_authed/files/index'
import { Route as AuthedDomainsIndexRouteImport } from './routes/_authed/domains/index'
import { Route as AuthedDatabasesIndexRouteImport } from './routes/_authed/databases/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFilesIndexRoute = AuthedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsIndexRoute = AuthedDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDatabasesIndexRoute = AuthedDatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/databases/': typeof AuthedDatabasesIndexRoute
  '/domains/': typeof AuthedDomainsIndexRoute
  '/files/': typeof AuthedFilesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthedIndexRoute
  '/databases': typeof AuthedDatabasesIndexRoute
  '/domains': typeof AuthedDomainsIndexRoute
  '/files': typeof AuthedFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/databases/': typeof AuthedDatabasesIndexRoute
  '/_authed/domains/': typeof AuthedDomainsIndexRoute
  '/_authed/files/': typeof AuthedFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/databases/'
    | '/domains/'
    | '/files/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/' | '/databases' | '/domains' | '/files'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/'
    | '/_authed/databases/'
    | '/_authed/domains/'
    | '/_authed/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/files/': {
      id: '/_authed/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthedFilesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/domains/': {
      id: '/_authed/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof AuthedDomainsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/databases/': {
      id: '/_authed/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof AuthedDatabasesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDatabasesIndexRoute: typeof AuthedDatabasesIndexRoute
  AuthedDomainsIndexRoute: typeof AuthedDomainsIndexRoute
  AuthedFilesIndexRoute: typeof AuthedFilesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDatabasesIndexRoute: AuthedDatabasesIndexRoute,
  AuthedDomainsIndexRoute: AuthedDomainsIndexRoute,
  AuthedFilesIndexRoute: AuthedFilesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
